controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

docs:
    path: /docs/{path}
    controller: App\Controller\DocsController::index
    requirements:
        path: .+
# app_pdf_view:
#     path: /view-pdf/{fileName}
#     controller: App\Controller\PdfController::viewPdf
